title: NewsLens
description: 철학적, 과학적 사고로 세상을 바라보는 블로그
baseurl: ""
url: "https://goadrider.github.io"
permalink: /:year/:month/:day/:title/
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 10
paginate_path: "/page/:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 