# NewsLens 블로그 설정
title: NewsLens
description: 철학적, 과학적 사고로 세상을 바라보는 블로그
baseurl: ""
url: "https://goadrider.github.io"

# 테마 설정
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 다국어 설정 (jekyll-polyglot)
languages: ["ko", "en"]
default_lang: "ko"
exclude_from_localization: ["assets", "images", "css", "js", "fonts"]
parallel_localization: true

# 사이트 설정
locale: "ko-KR"
timezone: Asia/Seoul
encoding: "utf-8"
markdown: kramdown

# 검색 설정 - 사이트 안정성을 위해 완전히 비활성화
search: false
search_provider: false
lunr:
  search_within_pages: false

# 출력 설정
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

# 콘텐츠 설정
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-polyglot
  - jekyll-remote-theme

# 기본 값
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "NewsLens"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# 저자 정보
author: NewsLens
email: contact@newslens.com
github_username: goadrider
