# 사이트 기본 설정
title: NewsLens
description: 철학적, 과학적 사고로 세상을 바라보는 블로그
author: NewsLens
email: your-email@example.com
baseurl: ""
url: "https://goadrider.github.io"
logo: "/assets/images/site-logo.png"

# 다국어 설정
default_lang: "en"
languages: ["en", "ko"]

# 소셜 미디어
twitter_username: newslens
github_username: goadrider
facebook_username: newslens
instagram_username: newslens

# 날짜 포맷
date_format: "%b %-d, %Y"
date_format_ko: "%Y년 %m월 %d일"

# 빌드 설정
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# 인피니티 스크롤 설정
infinite_scroll:
  enabled: true
  debug: false
  path: "/page/:num/"
  load_more_text:
    en: "Loading more posts..."
    ko: "더 많은 글 불러오는 중..."

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# 포함할 파일/폴더
include:
  - _pages

# 포함하지 않을 파일/폴더
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .gitignore
  - README.md
  
# 컬렉션
collections:
  pages:
    output: true
    permalink: /:path/

# 기본 값
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "NewsLens"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      lang: "en"
      lang-ref: "home"
  - scope:
      path: "index.ko.html"
    values:
      lang: "ko"
      lang-ref: "home" 