name: GitHub Pages 배포

on:
  push:
    branches:
      - main  # 기본 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Ruby 설정
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Jekyll로 사이트 빌드
        run: |
          bundle install
          bundle exec jekyll build
        
      - name: GitHub Pages에 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 