name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
    
    - name: Build site
      run: |
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production
        TZ: Asia/Seoul
        
    # main 브랜치에 직접 배포합니다 (github-pages 사용)
    - name: Commit built site
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f _site
        git commit -m "Built site for GitHub Pages - ${{ github.event.head_commit.message }}"
      continue-on-error: true
      
    - name: Push changes
      if: github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 